title: Stackbit Fjord Theme
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  category: categories
  series: series
  tag: tags
