title: Stackbit Fjord Theme
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  soin-de-moi: soin-de-moi
  series: series
  tag: tags
